# Generated by Django 5.2.9 on 2025-12-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosave', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articledraft',
            options={'ordering': ['-saved_at']},
        ),
        migrations.RemoveField(
            model_name='articledraft',
            name='created_at',
        ),
        migrations.AddField(
            model_name='articledraft',
            name='article_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articledraft',
            name='article_type',
            field=models.CharField(default='a', max_length=10),
        ),
        migrations.AddField(
            model_name='articledraft',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articledraft',
            name='comment_status',
            field=models.CharField(default='o', max_length=10),
        ),
        migrations.AddField(
            model_name='articledraft',
            name='save_type',
            field=models.CharField(choices=[('auto', 'auto'), ('manual', 'manual')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='articledraft',
            name='saved_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='articledraft',
            name='show_toc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articledraft',
            name='status',
            field=models.CharField(default='d', max_length=10),
        ),
    ]
