# Generated by Django 5.2.8 on 2025-11-26 15:14

import django.db.models.deletion
import django.utils.timezone
import interaction.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0006_alter_blogsettings_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_key', models.CharField(blank=True, help_text='session based identifier for anonymous visitors', max_length=64, null=True, unique=True, verbose_name='anonymous key')),
                ('fingerprint', models.CharField(blank=True, help_text='user agent + ip hash to mitigate abuse', max_length=128, verbose_name='fingerprint')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created time')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_actor', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'interaction actor',
                'verbose_name_plural': 'interaction actors',
            },
        ),
        migrations.CreateModel(
            name='FavoriteFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='folder name')),
                ('slug', models.SlugField(blank=True, max_length=120, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('allow_duplicates', models.BooleanField(default=False, help_text='allow the same article to be saved multiple times', verbose_name='allow duplicates')),
                ('share_token', models.CharField(default=interaction.models._default_share_token, max_length=32, unique=True, verbose_name='share token')),
                ('share_hits', models.PositiveIntegerField(default=0, verbose_name='share hits')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_folders', to='interaction.interactionactor', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'favorite folder',
                'verbose_name_plural': 'favorite folders',
                'ordering': ['-updated_time', '-created_time'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InteractionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like', 'like notification'), ('favorite', 'favorite notification')], max_length=16, verbose_name='type')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='payload')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created time')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='article')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interaction.favoritefolder', verbose_name='folder')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'interaction notification',
                'verbose_name_plural': 'interaction notifications',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='note')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created time')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='article')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='interaction.favoritefolder', verbose_name='folder')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interaction.interactionactor', verbose_name='added by')),
            ],
            options={
                'verbose_name': 'favorite item',
                'verbose_name_plural': 'favorite items',
                'indexes': [models.Index(fields=['article'], name='interaction_article_1e8f66_idx'), models.Index(fields=['created_time'], name='interaction_created_be44f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.BooleanField(default=True, verbose_name='is positive')),
                ('anonymous_key', models.CharField(blank=True, help_text='cached for quick duplicate checking', max_length=64, verbose_name='anonymous key')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='user agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip address')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created time')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='interaction.interactionactor', verbose_name='actor')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.article', verbose_name='article')),
            ],
            options={
                'verbose_name': 'like',
                'verbose_name_plural': 'likes',
                'indexes': [models.Index(fields=['article', 'created_time'], name='interaction_article_16f5f5_idx'), models.Index(fields=['anonymous_key'], name='interaction_anonymo_745fe5_idx')],
                'unique_together': {('article', 'actor')},
            },
        ),
    ]
