# Generated by Django 5.2.8 on 2025-12-17 15:40

import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogsettings_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_save_type',
            field=models.CharField(choices=[('auto', '自动'), ('manual', '手动')], default='manual', max_length=10, verbose_name='最后保存类型'),
        ),
        migrations.CreateModel(
            name='ArticleDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='title')),
                ('body', mdeditor.fields.MDTextField(blank=True, default='', verbose_name='body')),
                ('summary', models.TextField(blank=True, default='', verbose_name='summary')),
                ('save_type', models.CharField(choices=[('auto', '自动保存'), ('manual', '手动保存')], default='auto', max_length=10, verbose_name='保存类型')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存时间')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1, verbose_name='status')),
                ('comment_status', models.CharField(choices=[('o', 'Open'), ('c', 'Close')], default='o', max_length=1, verbose_name='comment status')),
                ('article_type', models.CharField(choices=[('a', 'Article'), ('p', 'Page')], default='a', max_length=1, verbose_name='type')),
                ('show_toc', models.BooleanField(default=False, verbose_name='show toc')),
                ('article_order', models.IntegerField(default=0, verbose_name='order')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='blog.article', verbose_name='关联文章')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章草稿',
                'verbose_name_plural': '文章草稿',
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['article', 'saved_at'], name='blog_articl_article_3c94c8_idx'), models.Index(fields=['author', 'saved_at'], name='blog_articl_author__18ada2_idx')],
            },
        ),
    ]
